baseURL = 'https://wesselpoelman.nl'
languageCode = 'en-us'
title = 'Wessel Poelman'
baseurl = "/"
ignoreFiles = ["_cache$"]

[permalinks]
post = "/posts/:year/:month/:day/:slug/"

[menu]
[[menu.main]]
name = "Home"
url = ""
weight = 1
[[menu.main]]
name = "Posts"
url = "posts/"
weight = 2
[[menu.main]]
name = "Publications"
url = "publications/"
weight = 99
[[menu.main]]
name = "[cv]"
url = "/data/poelman_cv_en.pdf"
weight = 100
[[menu.main]]
name = "Books"
url = "books/"
weight = 3
[[menu.main]]
name = "Quotes"
url = "quotes/"
weight = 4
[[menu.main]]
name = "EAR"
url = "ear/"
weight = 5
# [[menu.main]]
# name = "Tags"
# url = "tags/"
# weight = 4
# [[menu.main]]
# name = "Subscribe"
# url = "index.xml"

[markup]
[highlight]
codeFences = false
[goldmark]
[renderer]
unsafe = true

[module]
[[module.imports]]
path = "github.com/yihui/hugo-xmin"
